spring:
  application:
    name: tdd-activity
  datasource:
    url: ${PG_DATABASE_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
